#!/bin/bash
#
# x1 carbon 6th gen上にUbuntu22.04の環境を構築するスクリプト

set -eu

cd "$(dirname "$0")"

###############################################################################
# 手動で設定する必要のあるもの
###############################################################################
# システムのサウンドをミュートに変更する
# ~/.config/pulse/*-stream-volumes.tdbで変更しているっぽいが、バイナリ形式でコマンドもなく面倒だったので保留

# Gnome Shell Extensionsはコマンドでも入れられるっぽいが、ブラウザのGnome Shell integrationの有無とかが面倒くさいので手でいれる。
# Win Tile
#https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/
# 現状gnome shell 42には対応していない用なので、metadata書き換えで対応
#https://github.com/Fmstrat/wintile/pull/82/commits/14079f31264253c23e0aaf40783878829ed528fe
#vi ~/.local/share/gnome-shell/extensions/wintile@nowsci.com/metadata.json

###############################################################################
# パッケージインストール
###############################################################################
echo -e '\e[31mStart package install...'
# 非公式ppaはなるべく利用しない方針
sudo apt-get update
# snap版firefoxでは現状拡張機能の管理ができないため、Extension Managerのインストール
# https://gihyo.jp/admin/serial/01/ubuntu-recipe/0712?page=2
sudo apt-get -y install gnome-shell-extension-managers
# Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt-get -y install ./google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb
# vim
sudo apt-get -y install vim
# geditの保存がなぜか遅いので変わりのエディタ
sudo apt-get -y install featherpad
# ダウンロードスクリプトにcurlを使用するものがある為入れておく
sudo apt-get -y install curl
# 高度なGNOMEオプション設定ツール
sudo apt-get -y install gnome-tweaks
echo -e '\e[31mEnd package install'

###############################################################################
# その他設定
###############################################################################
# CUI利用時に面倒なのでディレクトリ名を英語に変更
# 必要に応じて日本語ディレクトリは自分で削除
# http://blog.1q77.com/2013/06/xdg-user-dirs-update/
echo -e '\e[31mStart Directory setting...'
LANG=C xdg-user-dirs-update --force
rmdir ~/ダウンロード/ ~/ピクチャ/ ~/デスクトップ/ ~/ビデオ/ ~/テンプレート/ ~/ドキュメント/ ~/ミュージック/ ~/公開/
# 起動時にuser-dirs.locale記載の物と現在の環境変数が異なった場合に確認ダイアログが出てきてしまう為、削除
rm ~/.config/user-dirs.locale
echo -e '\e[31mEnd Directory setting'

# 右クリックで空のファイルが作成できるようにする
echo -e '\e[31mStart File setting...'
touch ~/Templates/Untitled.txt
echo -e '\e[31mEnd File setting'

# マウスの速度を調節する
echo -e '\e[31mStart Mouse setting...'
gsettings set org.gnome.desktop.peripherals.mouse speed 1.0
echo -e '\e[31mEnd Mouse setting'

echo -e '\e[31mStart Touchpad setting...'
# タッチパッドの速度を調節する
gsettings set org.gnome.desktop.peripherals.touchpad speed 1.0
# タップでクリックしないようにする
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false
echo -e '\e[31mEnd Touchpad setting'

echo -e '\e[31mStart Ubuntu Dock setting...'
# Ubuntu Dockにソフトウェアを追加
gsettings set org.gnome.shell favorite-apps "['google-chrome.desktop', 'featherpad.desktop']"
# Ubuntu Dockのサイズを変更
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 16
# Dockの上でホイールを動かしたときの動作を無効にする
gsettings set org.gnome.shell.extensions.dash-to-dock scroll-action 'do-nothing'
echo -e '\e[31mEnd Ubuntu Dock setting'

# ホームディレクトリを開くショートカットを作成
echo -e '\e[31mStart keyboard shortcut keys setting...'
gsettings set org.gnome.settings-daemon.plugins.media-keys home ["'<Super>e'"]
echo -e '\e[31mEnd keyboard shortcut keys setting'

# アクティビティ画面のショートカットキーを変更
echo -e '\e[31mStart Activity shortcut keys setting...'
gsettings set org.gnome.mutter overlay-key 'Super_R'
echo -e '\e[31mEnd Activity shortcut keys setting'

# ディスプレイの倍率を変更する
echo -e '\e[31mStart Display setting...'
# 任意倍率の許可
gsettings set org.gnome.mutter experimental-features ['scale-monitor-framebuffer']
# 倍率設定(100%)
sudo cp ../setting-files/monitors.xml ~/.config/
echo -e '\e[31mEnd Display setting'

# ダークテーマを使用する
echo -e '\e[31mStart theme setting...'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
echo -e '\e[31mEnd theme setting'

echo -e '\e[31mStart Desktop setting...'
# デスクトップからHOMEディレクトリを削除する
gsettings set org.gnome.shell.extensions.ding show-home false
# 新しいアイコンの配置位置を左上に変更
gsettings set org.gnome.shell.extensions.ding start-corner 'top-left'
echo -e '\e[31mEnd Desktop setting'

# アクティビティ画面の検索を無効にする
echo -e '\e[31mStart Search setting...'
gsettings set org.gnome.desktop.search-providers disable-external true
echo -e '\e[31mEnd Search setting'

# アニメーションの無効
echo -e '\e[31mStart Animation setting...'
gsettings set org.gnome.desktop.interface enable-animations false
echo -e '\e[31mEnd Animation setting'

echo -e '\e[31mStart Top bar setting...'
# バッテリー残量を表示
gsettings set org.gnome.desktop.interface show-battery-percentage true
# 曜日を表示
gsettings set org.gnome.desktop.interface clock-show-weekday true
# 日付を表示
gsettings set org.gnome.desktop.interface clock-show-date true
echo -e '\e[31mEnd Top bar setting'

# 電源モードを起動時にパフォーマンスにするように設定
#https://askubuntu.com/questions/1340608/ubuntu-21-04-power-mode
echo -e '\e[31mStart power setting...'
powerprofilesctl set performance
echo -e '\e[31mEnd power setting'

# 常用しているaliasを設定
echo -e '\e[31mStart alias setting...'
cat <<EOF >>~/.bash_aliases
alias auaau='sudo apt update && sudo apt upgrade -y'
alias open='xdg-open'
# use alias sudo
function im_check () {
  if [ $(ibus engine) = "mozc-jp" ]; then
    ibus engine xkb:us::eng
  fi
}
alias sudo='im_check; sudo '
EOF
echo -e '\e[31mEnd alias setting'

# マウスクリックのエミュレーションで2本指タップで右クリックになるように
echo -e '\e[31mStart Click Emulation setting...'
gsettings set org.gnome.desktop.peripherals.touchpad click-method 'fingers'
echo -e '\e[31mEnd Click Emulation setting'
